In [1]:
from pyspark.sql import functions as F
from pyspark.sql.window import Window
from pyspark.sql.types import *
from pyspark.storagelevel import StorageLevel
from pyspark.sql.functions import udf

In [2]:
spark.conf.get("spark.sql.parquet.int96TimestampConversion")

In [3]:
list=[['[-0.08356357429744941, 0.08524966674774039, -0.0784185383554695, -0.21859354442123433, -0.06993846447509879, -0.01691160239319382, -0.009708906425531714]']]
df= spark.createDataFrame(list,['Feature'])
display(df)

Feature
"[-0.08356357429744941, 0.08524966674774039, -0.0784185383554695, -0.21859354442123433, -0.06993846447509879, -0.01691160239319382, -0.009708906425531714]"

In [4]:
df1=df.withColumn("Feature", (F.split(F.regexp_replace("Feature","\[|\]",""),',')).cast('array<float>'))
df1.printSchema()

In [5]:
import pandas as pd
import numpy as np
data_2 = { 'furniture': [np.NaN ,np.NaN ,np.NaN], 'myid': ['1-12', '0-11', '2-12'], 'clothing': ["pants", "shoes", "socks"]} 

df_1 = pd.DataFrame(data_2)
ddf_1 = spark.createDataFrame(df_1)
ddf_1.show()

In [6]:
def drop_null_columns(df):
    
    d=df.count()
    null_counts = df.select([F.count(F.when(F.col(c).isNull(), c)).alias(c) for c in df.columns]).collect()[0].asDict()
    to_drop = [k for k, v in null_counts.items() if v == d]
    df = df.drop(*to_drop)
    return df

In [7]:
ddf_2=drop_null_columns(ddf_1)
ddf_2.show()

In [8]:
a[0].a

In [9]:
ddf_1.count()

In [10]:
from pyspark.sql import functions as F

In [11]:
from pyspark.sql import functions as F
list=[[1001,50,'BS32 0HW']]
df= spark.createDataFrame(list,['customer_id','age','post_code'])
df.show()

In [12]:
df1=df.withColumn("useful_info", F.concat_ws("",(F.concat_ws(" ", F.lit('Customer'),F.col('customer_id'),F.lit('is'),F.col('age'),F.lit('years old and lives at'),F.col('post_code'))),F.lit(".")))

In [13]:
display(df1)

customer_id,age,post_code,useful_info
1001,50,BS32 0HW,Customer 1001 is 50 years old and lives at BS32 0HW.